import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import {
  renderPublicCaddyConfig,
  validateGatewayPort,
  validatePublicBaseUrl,
} from "../scripts/render-public-caddy.mjs";

test("renders the exact public hostname to the isolated public gateway port", () => {
  const rendered = renderPublicCaddyConfig({
    publicBaseUrl: "https://mcp.zssh.dev",
    gatewayPort: 8789,
  });
  assert.equal(
    rendered,
    [
      "# Generated by zSSH scripts/render-public-caddy.mjs.",
      "# Public OpenAI ingress only; keep the upstream loopback-only.",
      "mcp.zssh.dev {",
      "    reverse_proxy 127.0.0.1:8789",
      "}",
      "",
    ].join("\n"),
  );
  assert.doesNotMatch(rendered, /8788/);
});

test("accepts an operator-selected non-private high port", () => {
  assert.equal(validateGatewayPort("9443"), 9443);
  assert.match(
    renderPublicCaddyConfig({
      publicBaseUrl: "https://gateway.zssh.dev/",
      gatewayPort: "9443",
    }),
    /127\.0\.0\.1:9443/,
  );
});

test("fails closed on unsafe or placeholder public origins", () => {
  for (const value of [
    "",
    "http://mcp.zssh.dev",
    "https://user:pass@mcp.zssh.dev",
    "https://mcp.zssh.dev/path",
    "https://mcp.zssh.dev/?q=1",
    "https://localhost",
    "https://gateway.local",
    "https://127.0.0.1",
    "https://example.com",
    "https://mcp.example.com",
    "https://mcp.example.net",
    "https://mcp.example.org",
    "https://mcp.zssh.dev:8443",
  ]) {
    assert.throws(() => validatePublicBaseUrl(value), /ZSSH_PUBLIC_BASE_URL/);
  }
});

test("refuses the private zssh.service port and invalid port values", () => {
  for (const value of ["8788", "0", "1023", "65536", "abc", "87 89"]) {
    assert.throws(() => validateGatewayPort(value), /ZSSH_PUBLIC_GATEWAY_PORT/);
  }
});

test("CLI uses environment values and emits only the Caddy config", () => {
  const script = fileURLToPath(new URL("../scripts/render-public-caddy.mjs", import.meta.url));
  const result = spawnSync(process.execPath, [script], {
    encoding: "utf8",
    env: {
      ...process.env,
      ZSSH_PUBLIC_BASE_URL: "https://mcp.zssh.dev",
      ZSSH_PUBLIC_GATEWAY_PORT: "8789",
    },
  });

  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.stderr, "");
  assert.match(result.stdout, /^# Generated by zSSH/m);
  assert.match(result.stdout, /^mcp\.zssh\.dev \{$/m);
  assert.match(result.stdout, /reverse_proxy 127\.0\.0\.1:8789/);
});

test("CLI exits non-zero instead of rendering a documentation placeholder", () => {
  const script = fileURLToPath(new URL("../scripts/render-public-caddy.mjs", import.meta.url));
  const result = spawnSync(process.execPath, [script], {
    encoding: "utf8",
    env: {
      ...process.env,
      ZSSH_PUBLIC_BASE_URL: "https://mcp.example.com",
    },
  });

  assert.equal(result.status, 2);
  assert.equal(result.stdout, "");
  assert.match(result.stderr, /documentation-only example domain/);
});
